# server
http_server_address = ":8000"
dev_server_address =  ":9000"
admin_server_address = ":5726"

# image storage options 
storage_image_client_id = ""
storage_image_client_secret = ""
storage_image_disable_ssl = true

# imgage storage private 
storage_image_private_bucket = ""
storage_image_private_provider = "local"
storage_image_private_region = ""
storage_image_private_endpoint = ""
