# project configuration
# ${} variable will be replaced with environment variables in runtime

[servers]
    # only open main port to public
    [servers.main]
    address = "${MAIN_SERVER_ADDRESS}"
    [servers.debug]
    address = "${DEBUG_SERVER_ADDRESS}"
    [servers.admin]
    address = "${ADMIN_SERVER_ADDRESS}"

[log]
    level = "${LOG_LEVEL}"
    file = "${LOG_FILE}"
    use_color = ${LOG_USE_COLOR}

[resources]
    # object storage
    [[resources.object_storage]]
    name = "image-private"
    bucket = "${STORAGE_IMAGE_PRIVATE_BUCKET}"
    provider = "${STORAGE_IMAGE_PRIVATE_PROVIDER}"
    region = "${STORAGE_IMAGE_PRIVATE_REGION}"
    endpoint = "${STORAGE_IMAGE_PRIVATE_ENDPOINT}"
        [resources.object_storage.s3]
        client_id = "${STORAGE_IMAGE_CLIENT_ID}"
        client_secret = "${STORAGE_IMAGE_CLIENT_SECRET}"
        disable_ssl = ${STORAGE_IMAGE_DISABLE_SSL}
        force_path_style = ${STORAGE_IMAGE_FOCE_PATH_STYLE}
    
    # database
    [resources.database]
    # default options
    max_open_conns = 20 
    max_retry = 5
        [[resources.database.connect]]
        name = "users"
        driver = "postgres"
            [resources.database.connect.leader]
            dsn = "${DB_USER_LEADER_DSN}"
            [resources.database.connect.replica]
            dsn = "${DB_USER_REPLICA_DSN}"

        [[resources.database.connect]]
        name = "notifications"
        driver = "postgres"
            [resources.database.connect.leader]
            dsn = "${DB_NOTIFICATION_LEADER_DSN}"
            [resources.database.connect.replica]
            dsn = "${DB_NOTIFICATION_REPLICA_DSN}"

    # redis
    [resources.redis]
    max_active_conn = 100 
        [[resources.redis.connect]]
        name = "session"
        address = "${REDIS_SESSION_ADDRESS}"
        [[resources.redis.connect]]
        name = "image"
        address = "${REDIS_IMAGE_ADDRESS}"