# server
main_server_address = ":8000"
dev_server_address =  ":9000"
admin_server_address = ":5726"

# image storage options 
storage_image_client_id = ""
storage_image_client_secret = ""
storage_image_disable_ssl = true
storage_image_foce_path_style = true

# imgage storage private 
storage_image_private_bucket = "private-image"
storage_image_private_provider = "local"
storage_image_private_region = "sg1"
storage_image_private_endpoint = ""

# postgres database
db_user_leader_dsn = "postgres://projectdb:projectdb@localhost:5444/user?sslmode=disable"
db_user_replica_dsn = "postgres://projectdb:projectdb@localhost:5444/user?sslmode=disable"
db_notification_leader_dsn = "postgres://projectdb:projectdb@localhost:5444/notification?sslmode=disable"
db_notification_replica_dsn = "postgres://projectdb:projectdb@localhost:5444/notification?sslmode=disable"