# env file is a helper file for the project to set environment variable
# similar to .env file

# server
main_server_address = ":8000"
debug_server_address = ":9000"
admin_server_address = ":5726"

# log
log_level = "info"
log_file = "./projectlog/project.log"
log_use_color = true

# storage image options 
storage_image_client_id = ""
storage_image_client_secret = ""
storage_image_disable_ssl = true
storage_image_foce_path_style = true

# storage image private 
storage_image_private_bucket = "./debug/bucket/private-image"
storage_image_private_provider = "local"
storage_image_private_region = ""
storage_image_private_endpoint = ""

# image download options
image_private_download_proto = "http://"
image_private_download_host = ""
image_private_download_port = ":9000"
image_private_download_path = "/v1/image/view"

# postgres database
db_user_leader_dsn = "postgres://projectdb:projectdb@localhost:5444/users?sslmode=disable"
db_user_replica_dsn = "postgres://projectdb:projectdb@localhost:5444/users?sslmode=disable"
db_notification_leader_dsn = "postgres://projectdb:projectdb@localhost:5444/notifications?sslmode=disable"
db_notification_replica_dsn = "postgres://projectdb:projectdb@localhost:5444/notifications?sslmode=disable"

# redis database
redis_session_address = "localhost:6379"
redis_image_address = "localhost:6379"