users:
  dialect: postgres
  database: users 
  host: localhost
  port: 5444
  user: projectdb 
  password: projectdb 

notifications:
  dialect: postgres
  database: notifications 
  host: localhost
  port: 5444
  user: projectdb 
  password: projectdb 